# app/seed/config.py

DEFAULT_PASSWORD_HASH = "$2b$12$m3C2NbxMRF3d/9DMyQuWcuUvBVAtw/r2HwJq/lrluP8VAl80S/wiu"

# Organization
MIN_USERS_PER_ORGANIZATION = 5
MAX_USERS_PER_ORGANIZATION = 50

# Projects
MIN_PROJECTS_PER_ORGANIZATION = 10
MAX_PROJECTS_PER_ORGANIZATION = 20

# Tickets
MIN_TICKETS_PER_PROJECT = 10
MAX_TICKETS_PER_PROJECT = 40

# Project Code
PROJECT_CODE_LENGTH = 8

# Comment Limit
MAX_COMMENTS_PER_TICKET = 10
MIN_COMMENTS_PER_TICKET = 3
