"""Create initial schema

Revision ID: 3694d65cdeb5
Revises: 
Create Date: 2026-06-27 23:41:59.989439

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3694d65cdeb5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(length=15), nullable=True),
    sa.Column('nationality', sa.String(length=31), nullable=True),
    sa.Column('verification_token', sa.String(length=255), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    schema='app'
    )
    op.create_table('organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_table('permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_table('role',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    schema='app'
    )
    op.create_table('project',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=127), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['app.organization.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_project_organization_id'), 'project', ['organization_id'], unique=False, schema='app')
    op.create_table('role_permission',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['permission_id'], ['app.permission.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app.role.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint(
        "role_id",
        "permission_id",
        name="uq_role_permission",
    ),
    schema='app'
    )
    op.create_table('user_organization',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['app.organization.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['app.role.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_user_organization'),
    schema='app'
    )
    op.create_table('ticket',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('project_id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('parent_ticket_id', sa.UUID(), nullable=True),
    sa.Column('assigned_to', sa.UUID(), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('type', sa.String(length=30), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=True),
    sa.Column('expected_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expected_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_start_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('actual_end_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reason_for_delay', sa.Text(), nullable=True),
    sa.Column('hours_logged', sa.Integer(), nullable=False),
    sa.Column('demo_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('ticket_number', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['app.organization.id'], ),
    sa.ForeignKeyConstraint(['parent_ticket_id'], ['app.ticket.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['app.project.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    
    schema='app'
    )
    op.create_index(op.f('ix_app_ticket_assigned_to'), 'ticket', ['assigned_to'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ticket_organization_id'), 'ticket', ['organization_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ticket_parent_ticket_id'), 'ticket', ['parent_ticket_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ticket_project_id'), 'ticket', ['project_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_ticket_status'), 'ticket', ['status'], unique=False, schema='app')
    op.create_table('activity',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('field_name', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['app.ticket.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_activity_ticket_id'), 'activity', ['ticket_id'], unique=False, schema='app')
    op.create_table('comment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('has_attachment', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['app.ticket.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_comment_ticket_id'), 'comment', ['ticket_id'], unique=False, schema='app')
    op.create_table('attachment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ticket_id', sa.UUID(), nullable=True),
    sa.Column('comment_id', sa.UUID(), nullable=True),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('stored_file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('updated_by', sa.UUID(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.UUID(), nullable=True),
    sa.CheckConstraint('\n            (\n                ticket_id IS NOT NULL AND comment_id IS NULL\n            )\n            OR\n            (\n                ticket_id IS NULL AND comment_id IS NOT NULL\n            )\n            ', name='ck_attachment_parent'),
    sa.ForeignKeyConstraint(['comment_id'], ['app.comment.id'], ),
    sa.ForeignKeyConstraint(['created_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['ticket_id'], ['app.ticket.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['app.user.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by'], ['app.user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    schema='app'
    )
    op.create_index(op.f('ix_app_attachment_comment_id'), 'attachment', ['comment_id'], unique=False, schema='app')
    op.create_index(op.f('ix_app_attachment_ticket_id'), 'attachment', ['ticket_id'], unique=False, schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_attachment_ticket_id'), table_name='attachment', schema='app')
    op.drop_index(op.f('ix_app_attachment_comment_id'), table_name='attachment', schema='app')
    op.drop_table('attachment', schema='app')
    op.drop_index(op.f('ix_app_comment_ticket_id'), table_name='comment', schema='app')
    op.drop_table('comment', schema='app')
    op.drop_index(op.f('ix_app_activity_ticket_id'), table_name='activity', schema='app')
    op.drop_table('activity', schema='app')
    op.drop_index(op.f('ix_app_ticket_status'), table_name='ticket', schema='app')
    op.drop_index(op.f('ix_app_ticket_project_id'), table_name='ticket', schema='app')
    op.drop_index(op.f('ix_app_ticket_parent_ticket_id'), table_name='ticket', schema='app')
    op.drop_index(op.f('ix_app_ticket_organization_id'), table_name='ticket', schema='app')
    op.drop_index(op.f('ix_app_ticket_assigned_to'), table_name='ticket', schema='app')
    op.drop_table('ticket', schema='app')
    op.drop_table('user_organization', schema='app')
    op.drop_table('role_permission', schema='app')
    op.drop_index(op.f('ix_app_project_organization_id'), table_name='project', schema='app')
    op.drop_table('project', schema='app')
    op.drop_table('role', schema='app')
    op.drop_table('permission', schema='app')
    op.drop_table('organization', schema='app')
    op.drop_table('user', schema='app')
    # ### end Alembic commands ###
