"""add timestamps

Revision ID: d21772adf651
Revises: 0ded6d54e29a
Create Date: 2026-05-17 18:01:16.090523

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd21772adf651'
down_revision: Union[str, Sequence[str], None] = '0ded6d54e29a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('issues', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('projects', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    op.add_column('projects', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'updated_at', schema='app')
    op.drop_column('projects', 'created_at', schema='app')
    op.drop_column('issues', 'updated_at', schema='app')
    op.drop_column('issues', 'created_at', schema='app')
    # ### end Alembic commands ###
