"""add issue position

Revision ID: 6b54da338597
Revises: d21772adf651
Create Date: 2026-05-17 18:18:16.576282

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b54da338597'
down_revision: Union[str, Sequence[str], None] = 'd21772adf651'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('issues', sa.Column('position', sa.Integer(), nullable=True), schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('issues', 'position', schema='app')
    # ### end Alembic commands ###
