"""add organization to projects

Revision ID: b5c7a15341f4
Revises: 255d5195a41f
Create Date: 2026-05-17 23:14:44.919483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b5c7a15341f4'
down_revision: Union[str, Sequence[str], None] = '255d5195a41f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('organization_id', sa.UUID(), nullable=False), schema='app')
    op.create_foreign_key(None, 'projects', 'organizations', ['organization_id'], ['id'], source_schema='app', referent_schema='app')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', schema='app', type_='foreignkey')
    op.drop_column('projects', 'organization_id', schema='app')
    # ### end Alembic commands ###
