from enum import Enum


class NotificationType(str, Enum):
    MENTION = "MENTION"
    TICKET_ASSIGNED = "TICKET_ASSIGNED"

    # TODO: TO BE IMPLEMENTED LATER
    
    TICKET_UNASSIGNED = "TICKET_UNASSIGNED"
    COMMENT = "COMMENT"
    STATUS_CHANGED = "STATUS_CHANGED"
    PRIORITY_CHANGED = "PRIORITY_CHANGED"
    ATTACHMENT_ADDED = "ATTACHMENT_ADDED"
    HOURS_LOGGED = "HOURS_LOGGED"
    SUBTASK_CREATED = "SUBTASK_CREATED"
    PROJECT_INVITATION = "PROJECT_INVITATION"
    ROLE_CHANGED = "ROLE_CHANGED"
    DUE_DATE_CHANGED = "DUE_DATE_CHANGED"
    TICKET_COMPLETED = "TICKET_COMPLETED"
    TICKET_REOPENED = "TICKET_REOPENED"